### ISSUE TITLE
Using descriptive and concise link names for resources on topic pages

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#177]
**Why?**

- Quicker to navigate via JAWS 

**Todos**

1. Update _resource_ content model 
2. Update query
3. Update html templates

**Comment by emanelfy** [comment]
cc-ing @anikbrazeau re: content modelling and applying overarching naming conventions for consistency :)

**Comment by anikbrazeau** [comment]
@emanelfy @dylanzheng94 

I think we might possibly need a tech solution here, rather than a content solution? To solve if the card/link name sometimes differs from the page name as it did previously in Figma?

https://www.figma.com/file/e6Xroz1EQe7CSr3IeCnKs4/Talent-Resources-v1?node-id=2500%3A40232

Ex: 
<img width="1447" alt="Screen Shot 2022-08-02 at 2 53 12 PM" src="https://user-images.githubusercontent.com/38330843/182451636-3bed7c34-ef4a-46cf-ad1c-03d3acfb341a.png">

**Comment by anikbrazeau** [comment]
Having the category/role be secondary in emphasis to the H1 (Responsibilities/Competencies/Job postings/etc.) would be great.

Would also be good to apply the emphasized short-form H1 to the page title that appears in tabs to help people decipher which is which.

**Comment by ClementineHahn** [comment]
Non releveant anymore as the product went through several iterations making this issue non applicable. Plus service is winding down therfore no further work on this will happen.
