### ISSUE TITLE
Staging site appears to be listed on Google Search

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#273]
**Describe the feature request**
Staging seems to appear in organic Google searches?
-- as raised in Sprint Demo by @hillaryl (September 29, 2022)

**How to reproduce**
- Search `cds "learning resources"`

**Expected behavior**
Production and staging should be non-searchable.

**Screenshots**

<img width="848" alt="Screen Shot 2022-09-29 at 2 22 43 PM" src="https://user-images.githubusercontent.com/38330843/193112538-efed71b8-19aa-42e8-b8a3-6c58196f7ced.png">

**Comment by hillaryl** [comment]
I was able to reproduce this on mobile and desktop devices with no history of viewing or searching for Learning resources. I used the query 'cds "learning resources"' 

@anikbrazeau 
> **Expected behavior**
> Production ideally searchable, staging less so.

For soft launch, the plan was to keep production and staging non-searchable so that we could limit to internal sharing only. Seems like this was in our team documentation but not on trello or github. Propose changing this from a bug issue to a new feature request. @daine should I open a new issue or edit this one?

**Comment by anikbrazeau** [comment]
@hillaryl Oops! Sorry will edit this to be "New feature request" and to reflect that both should be non-searchable.

**Comment by daine** [comment]
I just submitted a request to remove staging from google search: https://search.google.com/search-console/removals?resource_id=sc-domain%3Alearning-resources.cdssandbox.xyz

![Screen Shot 2022-10-03 at 10 06 47 AM](https://user-images.githubusercontent.com/916044/193637157-26a6a30e-2e1f-484c-be46-47fc683705c2.png)

**Comment by daine** [comment]
I added the `en.staging.*` and `fr.staging.*` as it seems to still show those on the results

![Screen Shot 2022-10-03 at 2 25 37 PM](https://user-images.githubusercontent.com/916044/193686140-76a62f8c-7cf1-4d9f-af67-b9098d0a3c6d.png)

**Comment by daine** [comment]
![Screen Shot 2022-10-04 at 8 58 18 AM](https://user-images.githubusercontent.com/916044/193868041-3190066e-97f9-4348-8d78-9e0ae0c3c576.png)

**Comment by anikbrazeau** [comment]
@daine ✅ This appears to be solve for me when I search incognito/not on desktop and mobile.
